const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94759404990"
const SESSION_ID = "PRABATH-MD~nfhgSSKZ#4NZJW1cYGE_iYuLUmRi4gWF8YWE3FOKeopbwbYZ8HlU"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
